#!/bin/bash

# Icon mapping from phosphor to heroicons
declare -A icon_map

# Common mappings
icon_map["ArrowLeft"]="ArrowLeftIcon"
icon_map["ArrowRight"]="ArrowRightIcon"
icon_map["ArrowUp"]="ArrowUpIcon"
icon_map["ArrowDown"]="ArrowDownIcon"
icon_map["X"]="XMarkIcon"
icon_map["Plus"]="PlusIcon"
icon_map["Heart"]="HeartIcon"
icon_map["Star"]="StarIcon"
icon_map["Fire"]="FireIcon"
icon_map["Users"]="UsersIcon"
icon_map["User"]="UserIcon"
icon_map["Trophy"]="TrophyIcon"
icon_map["MapPin"]="MapPinIcon"
icon_map["MagnifyingGlass"]="MagnifyingGlassIcon"
icon_map["Camera"]="CameraIcon"
icon_map["Gift"]="GiftIcon"
icon_map["Check"]="CheckIcon"
icon_map["CheckCheck"]="CheckBadgeIcon"
icon_map["DotsThreeVertical"]="EllipsisVerticalIcon"
icon_map["DotsThree"]="EllipsisHorizontalIcon"
icon_map["CaretDown"]="ChevronDownIcon"
icon_map["CaretUp"]="ChevronUpIcon"
icon_map["CaretLeft"]="ChevronLeftIcon"
icon_map["CaretRight"]="ChevronRightIcon"
icon_map["Smiley"]="FaceSmileIcon"
icon_map["ThumbsUp"]="HandThumbUpIcon"
icon_map["PaperPlaneRight"]="PaperAirplaneIcon"
icon_map["Clock"]="ClockIcon"
icon_map["Calendar"]="CalendarIcon"
icon_map["BookmarkSimple"]="BookmarkIcon"
icon_map["Target"]="BookmarkIcon"
icon_map["Buildings"]="BuildingOfficeIcon"
icon_map["CurrencyCircleDollar"]="CurrencyDollarIcon"
icon_map["Image"]="PhotoIcon"
icon_map["ImageIcon"]="PhotoIcon"
icon_map["Sparkle"]="SparklesIcon"
icon_map["Bell"]="BellIcon"
icon_map["Gear"]="CogIcon"
icon_map["House"]="HomeIcon"
icon_map["List"]="ListBulletIcon"
icon_map["FunnelSimple"]="FunnelIcon"
icon_map["ShareNetwork"]="ShareIcon"
icon_map["Download"]="ArrowDownTrayIcon"
icon_map["Upload"]="ArrowUpTrayIcon"
icon_map["Play"]="PlayIcon"
icon_map["Pause"]="PauseIcon"
icon_map["Stop"]="StopIcon"
icon_map["Eye"]="EyeIcon"
icon_map["EyeSlash"]="EyeSlashIcon"
icon_map["Phone"]="PhoneIcon"
icon_map["Envelope"]="EnvelopeIcon"
icon_map["ChatCircle"]="ChatBubbleOvalLeftIcon"
icon_map["PencilSimple"]="PencilIcon"
icon_map["Trash"]="TrashIcon"
icon_map["Clipboard"]="ClipboardIcon"
icon_map["Warning"]="ExclamationTriangleIcon"
icon_map["Info"]="InformationCircleIcon"
icon_map["Question"]="QuestionMarkCircleIcon"
icon_map["Lock"]="LockClosedIcon"
icon_map["LockOpen"]="LockOpenIcon"
icon_map["SignOut"]="ArrowRightOnRectangleIcon"
icon_map["SignIn"]="ArrowLeftOnRectangleIcon"

echo "Icon mapping created"